# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gye Jin Lee
title: PhD Student
email: gyejinlee@gatech.edu
website: https://papr1ka2.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: gyejinlee
github_username:  papr1ka2
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Gye Jin. I am a first year PhD student at Georgia Tech. I am interested in software security and cryptography.

content:
  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      None yet. Hopefully in the future!
#   layout: list
#   content:
#       - layout: left
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PwnedNoMore
        link: todo
        # link_text: boringcompany.com
        sub_title: todo
        caption: todo
        quote: >
          todo
        description: | # this will include new lines to allow paragraphs
            todo

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2022 - 
        sub_title: PhD Computer Science
        quote: >
          todo?
        description: | # this will include new lines to allow paragraphs
          todo

          todo

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I have free time, I like to ...
      - climb (indoors bouldering mostly)
      - cook healthy meals
      - mix cocktails
      - play games

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
